name: BLOOP
targets:
  BLOOP:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - App
      - Models
      - Persistence
      - Services
      - ViewModels
      - Views
    capabilities:
      - capability: healthKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: bloop.hearth
        INFOPLIST_FILE: Info.plist
        DEVELOPMENT_TEAM: PXP453J347
        ENABLE_DEBUG_DYLIB: NO
        CODE_SIGN_ENTITLEMENTS: BLOOP.entitlements
    dependencies:
      - package: GoogleSignIn
        product: GoogleSignIn
packages:
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS.git
    from: 7.1.0
